# Generated by Django 5.0.2 on 2024-02-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(default='in cash', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
