# Generated by Django 5.0.3 on 2024-03-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_options_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_method',
        ),
    ]
