# Generated by Django 5.0.2 on 2024-02-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
