# Generated by Django 5.0.2 on 2024-03-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_lesson_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
    ]
