# Generated by Django 5.0.3 on 2024-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_id',
            field=models.CharField(default='prod_PjiClQUO0EILBU'),
        ),
    ]
