# Generated by Django 5.0.3 on 2024-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_course_price_alter_course_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='price_1OuFmBDF5H2Kx4xvVtyc8WHi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stripe_id',
            field=models.CharField(default='prod_PjjERgHF7tMqSL'),
        ),
    ]
