# Generated by Django 5.0.2 on 2024-03-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_course_price_alter_course_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='price_1OwTukDF5H2Kx4xvVWgolvJo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stripe_id',
            field=models.CharField(default='prod_Pm1yoLzDgi5F4v'),
        ),
    ]
